### ISSUE TITLE
Getting started code snippet not working due to invalid signature in before_dispatch

### ISSUE THREAD

**Issue by schnitzelbub** [bocadilloproject/bocadillo#108] opened 2019-01-23 10:48 UTC
The getting started code snippet of the `feature tour` is not working due to an invalid signature in `before_dispatch`:

https://github.com/bocadilloproject/bocadillo/blob/4ed444003c9b1d16f6da64808b5c378a63374b74/docs/getting-started/snippets/api.py#L80-L86

the response argument is missing and thus the code fails with:
```
TypeError: before_dispatch() takes 2 positional arguments but 3 were given
```

I will provide a PR for it.

**Comment by florimondmanca** [comment] 2019-01-23 10:50
Thanks for reporting this. I believe however this is a duplicate of #107 . I'm closing this one but you can provide the PR and link to #107. :+1:

**Closed by florimondmanca** 2019-01-23 10:50 UTC
Labels: Duplicate

**Comment by schnitzelbub** [comment] 2019-01-23 10:53
Sorry, I should have checked the issues first. I updated the PR.
