### ISSUE TITLE
API reference documentation

### ISSUE THREAD

**Issue by sodrooome** [bocadilloproject/bocadillo#316] opened 2019-06-26 06:20 UTC
**Is your feature request related to a problem? Please describe.**
when I read the API reference documentation in the `application.py` section, there seems to be a sentence that has not been linked to the `websocket` section/guide.

**Describe the solution you'd like**
it might be better if the documentation is corrected.

**Describe alternatives you've considered**
NA

**Implementation ideas**
Unfortunately, I don't know whether it's a typo or not 😄

**Additional context**
NA

**Comment by florimondmanca** [comment] 2019-06-26 06:50
Hi! Thanks for reporting this. I noticed there was a strange-looking "::bocadillo.websockets#WebSocket" in .add_websocket_route(), is this what you were referring to? I pushed a fix in #317. :-)

There are probably other examples of this which are caused by a change in pydocmd (the library used to convert docstrings to Markdown files).

If you see more, feel free to try and fix them based on the example in #317 😄

The format for links to the API documentation is "/api/<module_name>.md". For the guide, it is "/guide/<name>.md" (<name> being one of the Markdown files in docs/guide).

**Comment by sodrooome** [comment] 2019-06-26 15:21
yes, I noticed that too!

thank you for the answer and response, i'll try to fix it when I find something like that again

**Comment by florimondmanca** [comment] 2019-06-26 15:38
Sounds good! Since the original problem has been solved I'll close this. :-)

**Closed by florimondmanca** 2019-06-26 15:38 UTC
Labels: bug, docs
